export {
  Link,
  router,
  usePage,
  Deferred,
  useForm,
  Head,
} from "@inertiajs/react";

export {
  theme,
  Layout,
  Menu,
  notification,
  Breadcrumb,
  Tooltip,
  Popconfirm,
  Modal,
  Button,
  Select,
  Input,
  InputNumber,
  DatePicker,
  Popover,
  Checkbox,
  Tag,
  Card,
  Avatar,
  List,
  Collapse,
  Drawer,
  Divider,
  Upload,
  message,
  Image,
  Tabs,
  Typography,
  Spin,
  Dropdown,
  Form,
  Switch,
  TimePicker,
  Table,
  Space,

} from "antd";

export {
  PlusCircleOutlined,
  EditOutlined,
  DeleteOutlined,
  CloseOutlined,
  EyeInvisibleOutlined,
  EyeOutlined,
  MedicineBoxOutlined,
  FileDoneOutlined,
  BgColorsOutlined,
  DollarOutlined,
  MoreOutlined,
  PlusOutlined,
  MinusOutlined,
  UserOutlined,
  FolderAddOutlined,
  DiffOutlined,
  MinusCircleOutlined,
  SyncOutlined,
  AntDesignOutlined,
  UploadOutlined,
  EyeTwoTone,
  MailOutlined,
  PhoneOutlined,
  FolderOpenOutlined,
  FilePdfOutlined,
  FileOutlined,
  LockOutlined,
  UnlockOutlined,
  ArrowRightOutlined,
  GoogleOutlined,
  GooglePlusOutlined,
  FacebookOutlined,
  TwitterOutlined,
  UserSwitchOutlined,
  KeyOutlined,
  SafetyOutlined,
  UsergroupAddOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  CheckCircleOutlined,
  ProjectOutlined,
  GatewayOutlined,
  BankOutlined,
  BulbOutlined,
  SettingOutlined,
  CiOutlined,
  BranchesOutlined,
  CaretDownOutlined,
  LoginOutlined,
  LogoutOutlined,
  ExclamationCircleFilled,
  DownloadOutlined,
  BarChartOutlined,
  FileTextOutlined,
  FieldTimeOutlined,
  ScheduleOutlined,
  CreditCardOutlined,
  CloseCircleOutlined,
  UnorderedListOutlined,
  CheckCircleFilled,
  PrinterOutlined,
  DeleteFilled,
  DeleteTwoTone,
  ExclamationCircleOutlined,
  InfoCircleOutlined,
  CalendarOutlined,
  WalletOutlined,
  ClockCircleOutlined,
  HomeOutlined,
  ApartmentOutlined,
  CloudDownloadOutlined
} from "@ant-design/icons";

export { PhoneInput } from "react-international-phone";
export { useRoute } from "@ziggy";
import dayjs from "dayjs";
import isSameOrAfter from 'dayjs/plugin/isSameOrAfter';
import isSameOrBefore from 'dayjs/plugin/isSameOrBefore';
import isBetween from 'dayjs/plugin/isBetween';

dayjs.extend(isSameOrAfter);
dayjs.extend(isSameOrBefore);
dayjs.extend(isBetween);

export { dayjs };
