export {
  Link,
  router,
  usePage,
  Deferred,
  useForm,
  Head,
} from "@inertiajs/react";

export {
  theme,
  Layout,
  Menu,
  notification,
  Breadcrumb,
  Tooltip,
  Popconfirm,
  Modal,
  Button,
  Select,
  Input,
  InputNumber,
  DatePicker,
  Popover,
  Checkbox,
  Tag,
  Card,
  Avatar,
  List,
  Collapse,
  Drawer,
  Divider,
  Upload,
  message,
  Image,
  Tabs,
  Typography,
  Spin,
  Dropdown,
} from "antd";

export {
  PlusCircleOutlined,
  EditOutlined,
  DeleteOutlined,
  CloseOutlined,
  EyeInvisibleOutlined,
  EyeOutlined,
  MedicineBoxOutlined,
  FileDoneOutlined,
  BgColorsOutlined,
  DollarOutlined,
  MoreOutlined,
  PlusOutlined,
  MinusOutlined,
  UserOutlined,
  FieldTimeOutlined,
  FolderAddOutlined,
  DiffOutlined,
  MinusCircleOutlined,
  SyncOutlined,
  AntDesignOutlined,
  UploadOutlined,
  EyeTwoTone,
  MailOutlined,
  PhoneOutlined,
  FolderOpenOutlined,
  FilePdfOutlined,
  FileOutlined,
  LockOutlined,
  UnlockOutlined,
  ArrowRightOutlined,
  GoogleOutlined,
  GooglePlusOutlined,
  FacebookOutlined,
  TwitterOutlined,
  UserSwitchOutlined,
  KeyOutlined,
  SafetyOutlined,
  UsergroupAddOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  CheckCircleOutlined,
  ProjectOutlined,
  GatewayOutlined,
  BankOutlined,
  BulbOutlined,
  SettingOutlined,
  CiOutlined,
  BranchesOutlined,
  CaretDownOutlined,
  LogoutOutlined,
  ExclamationCircleFilled,
  DownloadOutlined,
} from "@ant-design/icons";

export { PhoneInput } from "react-international-phone";
export { useRoute } from "@ziggy";
import dayjs from "dayjs";
export { dayjs };
